server:
  error:
    include-stacktrace: never
    include-message: always

spring:
  datasource:
    #    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/smart_city?useSSL=false
    #    username: shazzar
    #    password: Las-jefa5

    url: postgres://bcttfrisctcomi:4d0c37e7f03c24961926c5e3451f930e786417662fd3c1aef712da8e7c79df04@ec2-3-208-79-113.compute-1.amazonaws.com:5432/dd7kvveiu5bqi
    username: bcttfrisctcomi
    password: 4d0c37e7f03c24961926c5e3451f930e786417662fd3c1aef712da8e7c79df04
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  token:
    prefix: Bearer
    validity: '18000'
  header:
    string: Authorization
  signing:
    key: signingkey
  authorities:
    key: roles

cloudinary:
  cloud_name: shazzar-smart-city
  api_key: '876746761995797'
  api_secret: v0lkQHJ3I2-ZY1OsE4NLgeSEUHg
