server:
  error:
    include-stacktrace: never
    include-message: always

spring:
  datasource:
    #    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/smart_city?useSSL=false
    #    username: shazzar
    #    password: Las-jefa5

    url: postgres://ttsyzjxaeicfgg:795172da615e5995b61e812e95af23fd78f55f8cc14a5dd91266494ce516e84e@ec2-3-208-79-113.compute-1.amazonaws.com:5432/db9gj86ump56jb
    username: ttsyzjxaeicfgg
    password: 795172da615e5995b61e812e95af23fd78f55f8cc14a5dd91266494ce516e84e
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  token:
    prefix: Bearer
    validity: '18000'
  header:
    string: Authorization
  signing:
    key: signingkey
  authorities:
    key: roles

cloudinary:
  cloud_name: shazzar-smart-city
  api_key: '876746761995797'
  api_secret: v0lkQHJ3I2-ZY1OsE4NLgeSEUHg
